### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by smiRaphi** [TelepathicGrunt/StructureLayoutOptimizer#3]
here's the error:
```log
java.lang.RuntimeException: Failed to read accessWidener file from mod structure_layout_optimizer
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:529)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:527)
	... 6 more
Exiting with ERROR
Process exited with code 2.
```
and the full log: https://mclo.gs/nOfhzhP

**Comment by TelepathicGrunt** [comment]
fixed now in v1.0.4
The non-remapped jar was uploaded by error through the gradle automation setup
