### ISSUE TITLE
Possible Incompatibility with Revamped Shipwrecks

### ISSUE THREAD

**Issue by Wpgradford** [TelepathicGrunt/StructureLayoutOptimizer#4]
When a shipwreck from Revamped Shipwrecks 1.1.0 is generated naturally, the game freezes up. It seems with the jigsaw tomfoolery I implemented in 1.1.0 doesn't play nicely with optimized structure layouts! A user also reported it crashing on a server. I'm free to chat about this on Discord if the cause isn't clear.

Here's the error:
```
[19:24:24] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.class_148: Exception generating new chunk
	at knot/net.minecraft.class_3898.method_60445(class_3898.java:681) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3215$class_4212.method_18859(class_3215.java:602) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3215$class_4212.method_16075(class_3215.java:611) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3215$class_4212.method_18857(class_3215.java:575) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3215.method_12121(class_3215.java:151) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_8402(class_1937.java:209) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4538.method_22342(class_4538.java:151) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_41522(class_2794.java:261) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_40146(class_2794.java:240) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_12103(class_2794.java:180) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3079.method_43905(class_3079.java:102) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3079.method_43914(class_3079.java:70) ~[client-intermediary.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_54313(class_2170.java:384) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_9249(class_2170.java:314) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_58590(class_3244.java:1433) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_44356(class_3244.java:1421) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "src" is null
	at knot/telepathicgrunt.structure_layout_optimizer.utils.GeneralUtils.copyAll(GeneralUtils.java:93) ~[structure_layout_optimizer-fabric-1.0.4.jar:?]
	at knot/telepathicgrunt.structure_layout_optimizer.utils.GeneralUtils.shuffleAndPrioritize(GeneralUtils.java:66) ~[structure_layout_optimizer-fabric-1.0.4.jar:?]
	at knot/net.minecraft.class_3781.redirect$znj000$structure_layout_optimizer$structureLayoutOptimizer$fasterJigsawListShuffling1(class_3781.java:520) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3781.method_16627(class_3781.java:120) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3778$class_4182.method_19306(class_3778.java:143) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3778.method_27230(class_3778.java:377) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3778.method_39824(class_3778.java:341) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3195$class_7150.method_44021(class_3195.java:156) ~[client-intermediary.jar:?]
	at knot/com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-8.0.16.jar:?]
	at knot/net.minecraft.class_3195$class_7150.method_44019(class_3195.java:154) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3195.method_41614(class_3195.java:168) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_41044(class_2794.java:518) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_41041(class_2794.java:500) ~[client-intermediary.jar:?]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at knot/net.minecraft.class_2794.method_16129(class_2794.java:453) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9310.method_57601(class_9310.java:37) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9770.method_60560(class_9770.java:33) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3898.method_60442(class_3898.java:666) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9761.method_60461(class_9761.java:101) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9759.method_60428(class_9759.java:148) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9759.method_60427(class_9759.java:125) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9759.method_60432(class_9759.java:76) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9759.method_60424(class_9759.java:61) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3898.method_60446(class_3898.java:700) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10171.method_63554(class_10171.java:88) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10178.method_63604(class_10178.java:21) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_156.method_64122(class_156.java:296) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10174.method_63592(class_10174.java:50) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_10174.run(class_10174.java:62) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```

My full log: https://mclo.gs/BIeufVD
The original report's log: https://mclo.gs/iiVL3XX

**Comment by TelepathicGrunt** [comment]
So they got a structure piece, that has jigsaw blocks all set with a priority greater than 0, which caused by code to crash due to an assumption. Will fix
